### ISSUE TITLE
Moving between blocks by clicking jumper

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#24]
Navigation would be massively improved by being able to click on an existing jumper and being taken to that block  ... or even the linked block appearing on the same screen.

**Comment by nick-prater** [comment]
As a single click is used to start editing the jumper, I propose a double-click to go to the linked block. Seem reasonable?

I like the idea of the linked block appearing on the same screen, but I'm putting that to one side for now, while we get other functionality in place.

**Comment by jonwcrew** [comment]
Yes agree!

**Comment by nick-prater** [comment]
As of commit c2d5cdefdaa0567c36a349a8acbd7193cd6ab161 double-clicking goes to the linked block, with the corresponding jumper field highlighted.

I'd prefer to dynamically reload and display the block data, rather than reload the whole page. It would make the system seem more responsive. I've spend several hours on this, but there are a lot of subtleties to make sure all references to the old block are cleaned up and it was introducing new bugs. Rather than hold up development, we'll live with a complete page load for now.
