### ISSUE TITLE
Going back to position on large frame

### ISSUE THREAD

**Issue by simonglobal** [nick-prater/kronekeeper#55]
When going from block view to frame view on a large frame, it would be good to automatically scroll to the last block position.

**Comment by jonwcrew** [comment]
I second this .. Its actually the only thing that becomes really irritating when you are using it a lot. 

Just to be really clear .. you are looking at block C50 in block view you click the frame link above and you see the frame displayed with A80 top Left.

Would be good to return to the frame with block C50 in the centre of the screen and highlighted in some way.

**Comment by nick-prater** [comment]
It's being worked on... Expect an update tomorrow :)

**Comment by nick-prater** [comment]
Just committing a solution for this. Actually I don't think you always want the last viewed block centred on the screen. On a small frame, where it would be visible anyway, I think this gets irritating too.

I'm using the following logic on returning to frame view from a block:
  * If the last viewed block is entirely visible, don't scroll.
  * If any part of the last viewed block is off the screen, scroll so that it's centred.

About to put this live. Let me know how you get on...

**Comment by jonwcrew** [comment]
Great solution, works great thank you !
